# This is a basic workflow to help you get started with Actions

name: W3C validator - incl php pages

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the main branch
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  w3c-validate:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          mkdir -p ../deploy
          cp -r * ../deploy
          ./.github/scripts/deploy.expect $SCP_AUTH
        shell: bash
        env:
          SCP_AUTH: ${{ secrets.SCP_AUTH }}

      - name: W3C Validator
        run: |
          ./.github/scripts/w3c-validate-all.sh
        shell: bash
        env:
          PAGE_AUTH: ${{ secrets.PAGE_AUTH }}

      - name: Cleanup
        run: rm -rf ../deploy
        shell: bash      